version: "2"
run:
  timeout: 3m
linters:
  default: none
  enable:
    - funlen
    - lll
  exclusions:
    paths:
      - .knots
      - tasks
  settings:
    funlen:
      lines: 99
      statements: -1
    lll:
      line-length: 100
