run:
  timeout: 3m
issues:
  exclude-dirs:
    - .knots
    - tasks
linters:
  disable-all: true
  enable:
    - funlen
    - lll
linters-settings:
  funlen:
    lines: 99
    statements: -1
  lll:
    line-length: 100
