// K-37 origin metadata: a sibling plaintext file alongside each
// encrypted bundle that records *how* every key got its current value.
// The file is plaintext because the *fact* that a value was provisioned
// vs. operator-set is metadata, not secret. Storing origins outside the
// encrypted bundle lets the rotate-after-removal flow pick out the
// auto-rotatable keys without forcing a bundle format change.
package store

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Origin is an opaque label for how a key's current value was set. It
// is *not* a security boundary — origin lives in plaintext alongside
// the encrypted bundle. It exists to drive UX decisions, namely the
// K-37 `recipient remove --rotate` flow which only auto-rotates keys
// whose origin is OriginProvision (since those values were generated
// by Thimble itself and can be safely regenerated).
type Origin string

const (
	// OriginProvision marks a value generated by `thimble provision`
	// (high-entropy random bytes, base64url-encoded). Safe to rotate
	// without operator interaction.
	OriginProvision Origin = "provision"

	// OriginAndSet marks a value sourced from the stdout of an
	// operator-supplied command via `thimble and-set`. Origin command
	// is unknown to us, so we cannot regenerate the value: the operator
	// has to rerun the producer.
	OriginAndSet Origin = "and-set"

	// OriginSet marks a value supplied by an operator via masked
	// prompt or piped input (set / create / update). Cannot be
	// auto-rotated; the operator has to re-set the value.
	OriginSet Origin = "set"
)

// OriginsFileSuffix is appended to <bundle>.env to form the origins
// filename. Sibling layout means listing namespaces by walking
// secrets/<app>/<env>.env.age picks up the origins file too.
const OriginsFileSuffix = ".origins.json"

// originsRecord is the on-disk shape: a small JSON object mapping
// dotenv key -> origin label. Format is intentionally minimal so the
// file stays human-readable in a `git diff` review.
type originsRecord struct {
	Version int               `json:"version"`
	Keys    map[string]string `json:"keys"`
}

// originsPath returns the absolute path to the origins file for
// (app, env). Mirrors the layout used by encryptAndWrite for the
// ciphertext: secrets/<app>/<env>.origins.json.
func (s *Store) originsPath(app, env string) string {
	return filepath.Join(s.root, app, env+OriginsFileSuffix)
}

// loadOrigins reads the origins file for (app, env). A missing file is
// not an error: legacy namespaces predate K-37 and are treated as if
// every key has Origin "" (which callers default to OriginSet). The
// returned map is always non-nil; callers can write into it directly
// before passing it back to saveOrigins.
func (s *Store) loadOrigins(app, env string) (map[string]Origin, error) {
	path := s.originsPath(app, env)
	// #nosec G304 -- path is computed from validated app/env names
	// inside the store root.
	b, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return map[string]Origin{}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read origins for %s/%s: %w", app, env, err)
	}
	var rec originsRecord
	if err := json.Unmarshal(b, &rec); err != nil {
		return nil, fmt.Errorf(
			"decode origins for %s/%s: %w", app, env, err,
		)
	}
	out := make(map[string]Origin, len(rec.Keys))
	for k, v := range rec.Keys {
		out[k] = Origin(v)
	}
	return out, nil
}

// encodeOrigins marshals origins into the canonical on-disk shape:
// keys sorted, two-space indent, trailing newline. Used by saveOrigins
// and by callers that need the bytes (e.g. the rotation rollback path
// keeps the prior bytes in memory).
func encodeOrigins(origins map[string]Origin) ([]byte, error) {
	keys := make([]string, 0, len(origins))
	for k := range origins {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	rec := originsRecord{Version: 1, Keys: make(map[string]string, len(keys))}
	for _, k := range keys {
		rec.Keys[k] = string(origins[k])
	}
	b, err := json.MarshalIndent(rec, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

// saveOrigins writes origins atomically to <root>/<app>/<env>.origins.json.
// Empty maps still produce a file: that way later mutations do not have
// to re-detect "origins not yet created".
func (s *Store) saveOrigins(app, env string, origins map[string]Origin) error {
	b, err := encodeOrigins(origins)
	if err != nil {
		return err
	}
	return atomicWrite(s.originsPath(app, env), b, 0o600)
}

// saveOriginsWithHook is the commit-step wrapper around saveOrigins
// that consults the test-only fault-injection hook. Production code
// passes through to saveOrigins; tests can install a hook to simulate
// a mid-flow failure and verify that the surrounding rollback logic
// leaves the manifest, bundle, and origins file in their pre-rotation
// state.
func (s *Store) saveOriginsWithHook(
	app, env string, origins map[string]Origin,
) error {
	if s.faults.failNextOriginsSave {
		s.faults.failNextOriginsSave = false
		return errFaultInjectionOriginsSave
	}
	return s.saveOrigins(app, env, origins)
}

// errFaultInjectionOriginsSave is the synthetic error returned when
// the test seam is armed. Defined as a package-level variable so
// tests can match on it via errors.Is.
var errFaultInjectionOriginsSave = errors.New(
	"fault-injection: origins.json save",
)

// faultHooks is a small struct of test-only fault-injection toggles.
// Production code never sets these; the test helpers in
// origins_export_test.go arm them.
type faultHooks struct {
	failNextOriginsSave bool
}

// originsSnapshotBytes returns a snapshot of the origins file contents
// for (app, env) suitable for rollback. Returns nil when no file
// exists. Used by the rotation flow so a partial failure can restore
// the prior state.
func (s *Store) originsSnapshotBytes(app, env string) ([]byte, error) {
	path := s.originsPath(app, env)
	// #nosec G304 -- path is computed from validated app/env names.
	b, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("snapshot origins for %s/%s: %w", app, env, err)
	}
	return b, nil
}

// restoreOriginsBytes rewrites the origins file to bytes (or removes
// the file when bytes is nil). Used as the rollback companion to
// originsSnapshotBytes.
func (s *Store) restoreOriginsBytes(app, env string, prior []byte) error {
	path := s.originsPath(app, env)
	if prior == nil {
		err := os.Remove(path)
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("remove origins on rollback: %w", err)
		}
		return nil
	}
	return atomicWrite(path, prior, 0o600)
}

// ParseOrigin maps a flag value to an Origin, returning an error for
// unknown labels. Empty input maps to OriginSet (the safe default for
// "operator-supplied"). Used by `--origin` flag parsing on the CLI.
func ParseOrigin(s string) (Origin, error) {
	trimmed := strings.TrimSpace(strings.ToLower(s))
	switch trimmed {
	case "", string(OriginSet):
		return OriginSet, nil
	case string(OriginProvision):
		return OriginProvision, nil
	case string(OriginAndSet):
		return OriginAndSet, nil
	default:
		return "", fmt.Errorf(
			"unknown origin %q; want one of provision, and-set, set",
			s,
		)
	}
}

// originOrDefault returns origins[key] when present, falling back to
// OriginSet so legacy namespaces (no origins file at all) and any
// pre-K-37 keys are treated as "operator-supplied".
func originOrDefault(origins map[string]Origin, key string) Origin {
	if existing, ok := origins[key]; ok && existing != "" {
		return existing
	}
	return OriginSet
}
